name: Build and Publish Obsidian RPM

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check version and download source
        run: bash check_version.sh

      - name: Install RPM Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm createrepo-c

      - name: Build RPM package
        run: |
          rpmbuild -bb obsidian.spec \
            --define "_version ${{ env.VERSION }}" \
            --define "_sourcedir $PWD" \
            --define "_rpmdir $PWD/output"

      - name: Setup RPM Repository directory
        run: |
          # Create the folder structure for the repository
          mkdir -p public/x86_64
          # Move the newly built RPM into the repository folder
          cp output/x86_64/*.rpm public/x86_64/

      - name: Generate Repository Metadata
        run: createrepo_c public/x86_64/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public